# Generated by Django 6.0.2 on 2026-02-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('IT Support', 'IT Support')], default='AWS', max_length=20),
        ),
    ]
